language: java
jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: AntonioDOrazio
    token: dc2335d5b5d0a04e46810cd2494f073afb2a1a8e
      secure:

script: 
  - ant build
  - sonar-scanner